version: '3.7'

services:
  api_analytics:
    build:
      args:
        NODE_ENV: development
      context: .
    command: 'npm run dev'
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - /app/node_modules
    container_name: api_analytics
