kind: Service
apiVersion: v1
metadata:
  labels:
    app: api-analytics
  name: api-analytics
  namespace: workshop

spec:
  type: NodePort
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000
    - name: http
      port: 9898
      protocol: TCP
      targetPort: 9898
  selector:
    app: api-analytics